package com.example.ashen.carfinder;

import java.util.UUID;

/**
 * Class representing a unique used car listing.
 */
public class CarListing implements Listing {
    //TODO: a uuid is used to uniquely identify this Listing, this value is generated by us
    // but should be provided by the API.
    private String  mUuid;
    private String  mMake;  // the make of the used car
    private String  mModel; // the model of the used car
    private String  mImage; // the image path
    private String  mDescription; // the description of the used car

    private int     mYear; // the manufacture year of the used car
    private int     mAskingPrice; // the asking price for the used car
    private int     mStandardPrice; // the standard price of the used car, this is an arbitrary value

    private boolean mIsBestInYear;  // whether the car was best in its year
    private boolean mIsWorstInYear; // whether the car was worst in its year
    private boolean mIsStarred; // has the car listing been starred

    /**
     * Constructs a new CarListing
     */
    public CarListing (UUID uuid, String make, String model, String image, String description,
                       int year, int askingPrice, int standardPrice, boolean isBestInYear,
                       boolean isWorstInYear, boolean isStarred) {
        this(uuid.toString(), make, model, image, description, year, askingPrice,
                standardPrice, isBestInYear, isWorstInYear, isStarred);
    }

    /**
     * Constructs a new CarListing
     */
    public CarListing (String uuid, String make, String model, String image, String description,
                       int year, int askingPrice, int standardPrice, boolean isBestInYear,
                       boolean isWorstInYear, boolean isStarred) {
        this.mUuid          = uuid;
        this.mMake          = make;
        this.mModel         = model;
        this.mImage         = image;
        this.mDescription   = description;
        this.mYear          = year;
        this.mAskingPrice   = askingPrice;
        this.mStandardPrice = standardPrice;
        this.mIsBestInYear  = isBestInYear;
        this.mIsWorstInYear = isWorstInYear;
        this.mIsStarred     = isStarred;
    }

    public String getUuid() {
        return mUuid;
    }

    public String getMake() {
        return mMake;
    }

    public String getModel() {
        return mModel;
    }

    public boolean isWorstInYear() {
        return mIsWorstInYear;
    }

    public boolean isBestInYear() {
        return mIsBestInYear;
    }

    public boolean isStarred() {
        return mIsStarred;
    }

    public int getStandardPrice() {
        return mStandardPrice;
    }

    public int getAskingPrice() {
        return mAskingPrice;
    }

    public int getYear() {
        return mYear;
    }

    public String getDescription() {
        return mDescription;
    }

    public String getImage() {
        return mImage;
    }

    public void setUuid(String uuid) {
        this.mUuid = uuid;
    }

    public void setMake(String make) {
        this.mMake = make;
    }

    public void setModel(String model) {
        this.mModel = model;
    }

    public void setImage(String image) {
        this.mImage = image;
    }

    public void setDescription(String description) {
        this.mDescription = description;
    }

    public void setYear(int year) {
        this.mYear = year;
    }

    public void setAskingPrice(int askingPrice) {
        this.mAskingPrice = askingPrice;
    }

    public void setStandardPrice(int standardPrice) {
        this.mStandardPrice = standardPrice;
    }

    public void setIsBestInYear(boolean isBestInYear) {
        this.mIsBestInYear = isBestInYear;
    }

    public void setIsWorstInYear(boolean isWorstInYear) {
        this.mIsWorstInYear = isWorstInYear;
    }

    public void setIsStarred(boolean isStarred) {
        this.mIsStarred = isStarred;
    }
}
